name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Generate phpunit.xml ${{ vars.SITE_ID }}
        shell: bash
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>
            <phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.3/phpunit.xsd"
              bootstrap="vendor/autoload.php"
              colors="true"
            >
              <testsuites>
                  <testsuite name="Test Suite">
                      <directory suffix="Test.php">./tests</directory>
                  </testsuite>
              </testsuites>

              <source>
                  <include>
                      <directory suffix=".php">./app</directory>
                      <directory suffix=".php">./src</directory>
                  </include>
              </source>

              <php>
                  <env name="SITE_ID" value="${{secrets.SITE_ID}}"/>
                  <env name="SITE_PASSWORD" value="${{secrets.SITE_PASSWORD}}"/>
                  <env name="SHOP_ID" value="${{secrets.SHOP_ID}}"/>
                  <env name="SHOP_PASSWORD" value="${{secrets.SHOP_PASSWORD}}"/>
                  <env name="PUBLIC_KEY" value="${{secrets.PUBLIC_KEY}}"/>
                  <env name="KEY_HASH" value="${{secrets.KEY_HASH}}"/>
              </php>
          </phpunit>' > phpunit.xml

      - name: Run test suite
        run: composer run-script test
